"""empty message

Revision ID: f818f940af8c
Revises: cd648a367de2
Create Date: 2019-09-20 03:49:08.899633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f818f940af8c'
down_revision = 'cd648a367de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'subscribed')
    # ### end Alembic commands ###
